import { useState } from 'react';
import { Link } from 'react-router-dom';
import { questions } from './questions';

function QuizWizard() {
  const [patientData, setPatientData] = useState({
    Age: '', Height: '', Weight: '', Gender: '', Education: '', Employment: '',
    Income: '', Ethnicity: '', Race: '', MedBackgrnd: '', Industry: '',
    Department: '', Stand: '', Profession: '', Insurance: ''
  });

  const [currentQuestionIndex, setCurrentQuestionIndex] = useState(0);
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [treatmentPlan, setTreatmentPlan] = useState(null);

  // Helper to safely update the specific field in our state object
  const handleInputChange = (fieldId, value) => {
    setPatientData(prev => ({
      ...prev,
      [fieldId]: value
    }));
  };

  const handleCheckboxToggle = (fieldId, option) => {
    setPatientData(prev => {
      const currentVal = prev[fieldId];
      // Split current string into an array, ignoring empty strings
      let selected = currentVal ? currentVal.split(',').map(s => s.trim()).filter(Boolean) : [];

      if (selected.includes(option)) {
        // Remove option if it's already selected
        selected = selected.filter(item => item !== option);
      } else {
        // Add option
        selected.push(option);
      }

      // Re-join into the comma-separated string expected by the backend
      return { ...prev, [fieldId]: selected.join(', ') };
    });
  };

  // API submission logic
  const submitToAPI = async () => {
    setIsSubmitting(true);

    try {
      // Coerce the continuous variables to floats to satisfy Pydantic
      const payload = {
        ...patientData,
        Age: parseFloat(patientData.Age),
        Height: parseFloat(patientData.Height),
        Weight: parseFloat(patientData.Weight),
        Stand: parseFloat(patientData.Stand)
      };

      const response = await fetch('http://127.0.0.1:8000/api/predict', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify(payload)
      });

      if (!response.ok) {
        const errorData = await response.json();
        throw new Error(JSON.stringify(errorData.detail));
      }

      const data = await response.json();
      setTreatmentPlan(data.recommendations);

    } catch (error) {
      console.error("API Error:", error);
      alert(`Failed to generate treatment plan. Error: ${error.message}`);
    } finally {
      setIsSubmitting(false);
    }
  };

  const handleNext = () => {
    if (currentQuestionIndex < questions.length - 1) {
      setCurrentQuestionIndex(prev => prev + 1);
    } else {
      submitToAPI()
    }
  };

  const handleBack = () => {
    setCurrentQuestionIndex(prev => prev - 1);
  };

  const currentQuestion = questions[currentQuestionIndex];
  const currentValue = patientData[currentQuestion.id];
  const isLastQuestion = currentQuestionIndex === questions.length - 1;

  // Results rendering
  if (treatmentPlan) {
    // 1. Sort all treatments by probability (highest to lowest)
    const sortedTreatments = Object.entries(treatmentPlan).sort((a, b) => b[1] - a[1]);

    // 2. Define keywords to identify OTC/Medication items
    const otcKeywords = [
      'acetaminophen', 'tylenol', 'aspirin', 'bayer', 'ibuprofen', 'naproxen',
      'aleve', 'motrin', 'advil', 'aspercreme', 'orthosis', 'brace', 'voltaren',
      'capsaicin', 'cream', 'gel', 'icy hot', 'heating pad', 'fish oil', 'ice pack', 'biofreeze', 'salonpas', 'orthosis', 'glucosamine', 'turmeric', 'bengay', 'tiger balm', 'chondroitin', 'msm', 'electric'
    ];

    // 3. Separate the sorted treatments into two arrays
    const otcResults = [];
    const exerciseResults = [];

    sortedTreatments.forEach(([name]) => {
      const lowerName = name.toLowerCase();
      // If the treatment name contains an OTC keyword, put it in OTCs. Otherwise, Exercises.
      if (otcKeywords.some(kw => lowerName.includes(kw))) {
        otcResults.push(name);
      } else {
        exerciseResults.push(name);
      }
    });

    // 4. Grab only the top 3 from each category
    const topOTCs = otcResults.slice(0, 3);
    const topExercises = exerciseResults.slice(0, 3);

    return (
        <div className="flex flex-col items-center py-12 px-4 font-sans">
          <div className="w-full max-w-2xl bg-white p-8 rounded-xl shadow-lg border border-slate-200">
            <div className="text-center mb-10">
              <h1 className="text-4xl font-bold mb-2 text-blue-700">Your Treatment Plan</h1>
              <p className="text-slate-500">Personalized recommendations generated by KneeBot</p>
            </div>

            <div className="flex flex-col gap-10">
              {/* OTC Section */}
              <section>
                <h2 className="text-2xl font-bold text-slate-800 mb-4 border-b border-slate-200 pb-2">Top OTC Options</h2>
                <div className="space-y-3">
                  {topOTCs.length > 0 ? (
                      topOTCs.map((treatment, index) => (
                          <div key={treatment} className="bg-slate-50 p-4 rounded-lg border border-slate-200 flex items-center gap-4 shadow-sm">
                        <span className="flex items-center justify-center w-8 h-8 rounded-full bg-blue-100 text-blue-700 font-bold text-lg flex-shrink-0">
                          {index + 1}
                        </span>
                            <span className="text-lg font-medium text-slate-800">{treatment}</span>
                          </div>
                      ))
                  ) : (
                      <p className="text-slate-500 italic">No OTC recommendations for this profile.</p>
                  )}
                </div>
              </section>

              {/* Exercises Section */}
              <section>
                <h2 className="text-2xl font-bold text-slate-800 mb-4 border-b border-slate-200 pb-2">Top Exercises</h2>
                <div className="space-y-3">
                  {topExercises.length > 0 ? (
                      topExercises.map((treatment, index) => (
                          <div key={treatment} className="bg-slate-50 p-4 rounded-lg border border-slate-200 flex items-center gap-4 shadow-sm">
                        <span className="flex items-center justify-center w-8 h-8 rounded-full bg-blue-100 text-blue-700 font-bold text-lg flex-shrink-0">
                          {index + 1}
                        </span>
                            <span className="text-lg font-medium text-slate-800">{treatment}</span>
                          </div>
                      ))
                  ) : (
                      <p className="text-slate-500 italic">No exercise recommendations for this profile.</p>
                  )}
                </div>
              </section>
            </div>

            <div className="flex flex-col gap-4 mt-12 pt-8 border-t border-slate-200">
              <button
                  onClick={() => {
                    setTreatmentPlan(null);
                    setCurrentQuestionIndex(0);
                    setPatientData({
                      Age: '', Height: '', Weight: '', Gender: '', Education: '', Employment: '',
                      Income: '', Ethnicity: '', Race: '', MedBackgrnd: '', Industry: '',
                      Department: '', Stand: '', Profession: '', Insurance: ''
                    });
                  }}
                  className="w-full px-6 py-4 bg-slate-100 hover:bg-slate-200 text-slate-800 rounded-lg text-xl font-bold transition-colors"
              >
                Start Over
              </button>

              <Link
                  to="/"
                  className="w-full px-6 py-4 bg-transparent border-2 border-slate-300 hover:border-slate-400 text-slate-600 rounded-lg text-xl font-bold text-center transition-colors"
              >
                Return to Home
              </Link>
            </div>
          </div>
        </div>
    );
  }

  // Quiz rendering
  return (
      <div className="flex flex-col items-center py-12 px-4 font-sans">
        <div className="w-full max-w-2xl">

          <div className="text-center mb-8">
            <h1 className="text-4xl font-bold mb-2 text-slate-900">KneeBot</h1>
            <p className="text-slate-500 text-lg">Personalized Joint Pain Management</p>
          </div>

          <div className="bg-white p-8 rounded-xl shadow-lg border border-slate-200">

            {/* Progress Indicator */}
            <div className="mb-8">
              <div className="flex justify-between text-sm text-slate-500 mb-2">
                <span>Question {currentQuestionIndex + 1} of {questions.length}</span>
                <span>{Math.round(((currentQuestionIndex) / questions.length) * 100)}%</span>
              </div>
              <div className="w-full bg-slate-200 rounded-full h-2.5">
                <div
                    className="bg-blue-600 h-2.5 rounded-full transition-all duration-300"
                    style={{ width: `${((currentQuestionIndex) / questions.length) * 100}%` }}
                ></div>
              </div>
            </div>

            {/* Active Question Render */}
            <div className="mb-8 min-h-[200px]">
              <h2 className="text-2xl font-semibold mb-6 text-slate-800">{currentQuestion.text}</h2>

              {currentQuestion.type === 'number' ? (
                  <input
                      type="number"
                      value={currentValue}
                      onChange={(e) => handleInputChange(currentQuestion.id, e.target.value)}
                      placeholder={currentQuestion.placeholder}
                      className="w-full text-2xl p-4 bg-slate-50 border border-slate-300 rounded-lg text-slate-900 focus:outline-none focus:border-blue-500 focus:ring-1 focus:ring-blue-500 transition-colors"
                  />
              ) : currentQuestion.type === 'checkbox' ? (
                  <div className="flex flex-col gap-3">
                    {currentQuestion.options.map((option) => {
                      const isSelected = currentValue ? currentValue.split(', ').includes(option) : false;
                      return (
                          <button
                              key={option}
                              onClick={() => handleCheckboxToggle(currentQuestion.id, option)}
                              className={`p-4 text-left rounded-lg text-lg transition-all flex items-center gap-4 ${
                                  isSelected
                                      ? 'bg-blue-50 border-2 border-blue-500 font-medium text-blue-900'
                                      : 'bg-white border-2 border-slate-200 hover:bg-slate-50 text-slate-700'
                              }`}
                          >
                            {/* Visual Checkbox Indicator */}
                            <div className={`w-6 h-6 rounded flex-shrink-0 border-2 flex items-center justify-center transition-colors ${
                                isSelected ? 'border-blue-500 bg-blue-500' : 'border-slate-300 bg-white'
                            }`}>
                              {isSelected && <span className="text-white text-sm font-bold">✓</span>}
                            </div>
                            {option}
                          </button>
                      );
                    })}
                  </div>
              ) : (
                  <div className="flex flex-col gap-3">
                    {currentQuestion.options.map((option) => (
                        <button
                            key={option}
                            onClick={() => handleInputChange(currentQuestion.id, option)}
                            className={`p-4 text-left rounded-lg text-lg transition-all ${
                                currentValue === option
                                    ? 'bg-blue-50 border-2 border-blue-500 font-medium text-blue-900'
                                    : 'bg-white border-2 border-slate-200 hover:bg-slate-50 text-slate-700'
                            }`}
                        >
                          {option}
                        </button>
                    ))}
                  </div>
              )}
            </div>

            {/* Navigation Controls */}
            <div className="flex justify-between mt-8 border-t border-slate-200 pt-6">
              <button
                  onClick={handleBack}
                  disabled={currentQuestionIndex === 0}
                  className="px-6 py-3 bg-slate-100 text-slate-700 hover:bg-slate-200 disabled:opacity-50 disabled:cursor-not-allowed rounded-lg text-lg font-medium transition-colors"
              >
                Back
              </button>

              <button
                  onClick={handleNext}
                  disabled={!currentValue}
                  className="px-8 py-3 bg-blue-600 text-white hover:bg-blue-700 disabled:opacity-50 disabled:cursor-not-allowed rounded-lg text-lg font-bold transition-colors"
              >
                {isLastQuestion ? 'Get Treatment Plan' : 'Next'}
              </button>
            </div>
            <div className="text-center mt-6">
              <Link to="/" className="text-blue-600 hover:text-blue-800 underline transition-colors">
                Cancel and return to Home
              </Link>
            </div>

          </div>
        </div>
      </div>
  );
}

export default QuizWizard;